spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9b104.p.ssafy.io:3306/oz?useSSL=false
    username: fire4bird
    password: fire4bird

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
jwt:
  secret-key: asdasdasdasdasdasdasdassdasdasdasdasdassdasd
  access-token-valid-time: 60000
  refresh-token-valid-time: 60000

kakao:
  client-id: 581ca2cce261061e9424b527fdadf174
  redirect-uri: http://localhost:8080/api/oauth/kakao
  token-url: https://kauth.kakao.com/oauth/token
  info-url: https://kapi.kakao.com/v2/user/me

