spring:
  profiles:
    active: local
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #   배포된 db
        # url: 지우기
        # username: 지우기
        # password: 지우기
    #    배포 db 쓰려면 여기까지 3줄 주석 제거
    #   로컬 db
#    url: 지우기
#    username: 지우기
#    password: 지우
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    # username: 지우기
    # password: 지우기
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

  redis:
    # host: 지우기
    host: localhost
    port: 6379
    # password: 지우기

jwt:
  # secret-key: 지우기
  access-token-valid-time: 60000
  refresh-token-valid-time: 60000

kakao:
  # client-id: 
  redirect-uri: https://i9b104.p.ssafy.io/kakaoLogin
  token-url: https://kauth.kakao.com/oauth/token
  info-url: https://kapi.kakao.com/v2/user/me
