spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oz?serverTimezone=UTC
    username: root
    password: ssafy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  secret-key: asdasdasdasdasdasdasdassdasdasdasdasdassdasd
  access-token-valid-time: 60000
  refresh-token-valid-time: 60000

kakao:
  client-id: 581ca2cce261061e9424b527fdadf174
  redirect-uri: http://localhost:8080/api/oauth/kakao
  token-url: https://kauth.kakao.com/oauth/token
  info-url: https://kapi.kakao.com/v2/user/me

